import _ from 'lodash'
import { useState, useEffect } from 'react'
import pluralize from 'pluralize'
import {
  Box,
  Typography,
  Tooltip,
  Button,
  IconButton,
  Dialog,
  DialogContent,
  TextField,
  Select,
  MenuItem,
  useTheme,
} from '@mui/material'
import { DebounceInput } from 'react-debounce-input'

import { useSystem, useRoster, useRosterErrors, usePath, useFs, useNative, useConfirm } from '../../Context'
import SelectSystem from '../../repo/SelectSystem'
import Roster from '../../Roster'
import { saveRoster, downloadRoster } from '../../repo/rosters'
import SelectionModal from '../../Force/SelectionModal'
import SelectForce from '../../Force/SelectForce'
import ViewRoster from '../../ViewRoster'
import { refreshRoster } from '../../utils'
import EditSystem from '../../repo/EditSystem'
import { pathToForce, validateRoster } from '../../validate'
import discordIcon from '../../discord-icon.png'
import githubIcon from '../../github-icon.png'

const Body = ({ children, systemInfo, setSystemInfo }) => {
  const [roster, setRoster] = useRoster()
  const confirmLeaveRoster = useConfirm(
    roster?.__.updated,
    `${roster?.__.filename} has not been saved. Are you sure you want to close it?`,
  )
  const system = useSystem()
  const [path, setPath] = usePath()

  const [open, setOpen] = useState(false)
  const { fs, rosterPath } = useFs()

  return (
    <Box className="container">
      <Tooltip id="tooltip" />
      <Box component="header">
        <Box component="nav">
          <ul>
            <li>
              <Typography
                variant="h6"
                data-tooltip-id="tooltip"
                data-tooltip-html="BlueScribe is an army list builder for tabletop wargames; it is heavily inspired by and 100% compatible with BattleScribe, reading the same format datafiles and writing rosters in the same format.<br /><br />No tracking, no subscription, no paid features. BlueScribe is GNU GPL 3.0 licensed."
              >
                BlueScribe
              </Typography>
              <IconButton href="https://discord.gg/m4q2BbxDQV" target="_blank" color="inherit">
                <img className="icon" src={discordIcon} alt="Discord" title="Discord" />
              </IconButton>
              <IconButton href="https://github.com/BlueWinds/bluescribe" target="_blank" color="inherit">
                <img className="icon" src={githubIcon} alt="Github" title="Github" />
              </IconButton>
              <Box>
                <Typography variant="caption">{packageJson.version}</Typography>
              </Box>
            </li>
            {roster && (
              <li>
                <SelectForce value={pathToForce(path)} onChange={setPath} fullWidth>
                  <MenuItem value="">Manage Roster</MenuItem>
                </SelectForce>
              </li>
            )}
          </ul>
          {system && (
            <ul>
              {roster && (
                <li>
                  <Button variant="outlined" onClick={() => setOpen(!open)}>
                    View/Print
                  </Button>
                </li>
              )}
              {roster && (
                <li>
                  <Button variant="outlined" onClick={() => downloadRoster(roster)}>
                    Download
                  </Button>
                </li>
              )}
              {roster && (
                <li>
                  <Button
                    variant="outlined"
                    disabled={!roster.__.updated}
                    onClick={async () => {
                      await saveRoster(roster, fs, rosterPath)
                      setRoster(roster, false)
                    }}
                  >
                    Save
                  </Button>
                </li>
              )}
              <li>
                <details role="list" dir="rtl">
                  <summary aria-haspopup="listbox" role="link">
                    ≡
                  </summary>
                  <ul role="listbox">
                    {roster && (
                      <li
                        data-tooltip-id="tooltip"
                        data-tooltip-html="This can be useful if the game system has been updated or if the roster was generated by a different tool and something seems incorrect."
                      >
                        <Typography
                          role="link"
                          onClick={() => {
                            document.querySelectorAll('details').forEach((d) => d.removeAttribute('open'))
                            setRoster(refreshRoster(roster, system))
                          }}
                        >
                          Refresh Roster
                        </Typography>
                      </li>
                    )}
                    {roster && (
                      <li data-tooltip-id="tooltip" data-tooltip-html="Load a different roster">
                        <Typography
                          role="link"
                          onClick={async () =>
                            await confirmLeaveRoster(() => {
                              document.querySelectorAll('details').forEach((d) => d.removeAttribute('open'))
                              setPath('')
                              setRoster()
                            })
                          }
                        >
                          Roster
                          <Box>
                            <Typography variant="caption">{roster.__.filename.split('/').at(-1)}</Typography>
                          </Box>
                        </Typography>
                      </li>
                    )}
                    <li data-tooltip-id="tooltip" data-tooltip-html="Load a different game system">
                      <Typography
                        role="link"
                        onClick={async () =>
                          await confirmLeaveRoster(() => {
                            document.querySelectorAll('details').forEach((d) => d.removeAttribute('open'))
                            setPath('')
                            setRoster()
                            setSystemInfo({ name: systemInfo.name })
                          })
                        }
                      >
                        Game System
                        <Box>
                          <Typography variant="caption">{system?.gameSystem.name}</Typography>
                        </Box>
                      </Typography>
                    </li>
                  </ul>
                </details>
              </li>
            </ul>
          )}
        </Box>
      </Box>
      {children}
      <SelectionModal open={open} setOpen={setOpen}>
        {roster && <ViewRoster />}
      </SelectionModal>
    </Box>
  )
}

function App() {
  const [loading, setLoading] = useState(false)
  const [gameData, setGameData] = useState(null)

  const [systemInfo, setInfo] = useState(JSON.parse(localStorage.system || '{}'))

  const setSystemInfo = (info) => {
    localStorage.system = JSON.stringify(info)
    setInfo(info)
  }
  const [mode, setMode] = useStorage(localStorage, 'dataMode', 'editRoster')

  const [roster, setRoster] = useState(null)
  const [openCategories, setOpenCategories] = useState({})
  const [currentPath, setCurrentPath] = useState('')
  const { fs, gameSystemPath } = useFs()
  const { readFilesNative } = useNative()

  useEffect(() => {
    const load = async () => {
      if (mode === 'editRoster') {
        try {
          console.log('System: ' + systemInfo.name, gameSystemPath)
          const systemPath = path.join(gameSystemPath, systemInfo.name)
          var dataPath = systemPath
          if (systemInfo.externalPath) {
            dataPath = systemInfo.externalPath
          }
          setGameData(await readFiles(dataPath, fs, systemPath, readFilesNative))
        } catch (e) {
          console.log(e)
          setSystemInfo({})
        }
        setLoading(false)
      }
    }

    if (systemInfo.battleScribeVersion) {
      setLoading(true)
      load()
    }
  }, [systemInfo, mode, fs, gameSystemPath, readFilesNative])

  window.gameData = gameData

  if (loading) {
    return (
      <Body systemInfo={systemInfo} setSystemInfo={setSystemInfo}>
        <BounceLoader color="#36d7b7" className="loading" />
      </Body>
    )
  }

  if (!systemInfo?.battleScribeVersion) {
    return (
      <Body systemInfo={systemInfo} setSystemInfo={setSystemInfo}>
        <SelectSystem setSystemInfo={setSystemInfo} setMode={setMode} previouslySelected={systemInfo} />
      </Body>
    )
  }

  if (mode === 'editSystem') {
    return <EditSystem systemInfo={systemInfo} setSystemInfo={setSystemInfo} />
  }

  const errors = validateRoster(roster, gameData)
  window.errors = errors

  return (
    <GameContext.Provider value={gameData}>
      <RosterContext.Provider value={[roster, setRoster]}>
        <RosterErrorsContext.Provider value={errors}>
          <OpenCategoriesContext.Provider value={[openCategories, setOpenCategories]}>
            <PathContext.Provider value={[currentPath, setCurrentPath]}>
              <Body systemInfo={systemInfo} setSystemInfo={setSystemInfo}>
                <ErrorBoundary
                  fallbackRender={({ error, resetErrorBoundary }) => {
                    return (
                      <SelectSystem
                        setSystemInfo={(i) => {
                          resetErrorBoundary()
                          setSystemInfo(i)
                        }}
                        setMode={setMode}
                        previouslySelected={systemInfo}
                        error={error}
                      />
                    )
                  }}
                >
                  <Roster />
                </ErrorBoundary>
              </Body>
            </PathContext.Provider>
          </OpenCategoriesContext.Provider>
        </RosterErrorsContext.Provider>
      </RosterContext.Provider>
    </GameContext.Provider>
  )
}

export default App
